---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-grafana-admin
  namespace: agentic-platform
spec:
  encryptedData:
    admin-password: AgBKK9vYcR9fR+KnprtblgUNFjRIquiVF8M1lvNVcl/ZbE0Xg/5swU/Zw+ouGhcrpjGU3BAI9li4T0RzgaUc+Nt3cZqxMUx7oJn39xlquQLfMeWGeY6R3b8xQJKV6AEMKiXm3BFQ3Pd2yILxviR6nWeobIdP3Y8A9jX/Hr3uWB1uFaqRsnYbpQ+9JHQNl3AWMmduEci2wIkjYPrEVF6/aGK/VCW5rHL1VXa++oWB7VV0/OoqtdP9vwk4HKAxfjIWFG4kA3icO3HmlF/8pUTeBEUIo22eg0dI+LmGWgaOXMa+c90FM/7R43n1RaUkcQGnVniQZieOXhSMdPRPE0dwfaltcr/Og97kdDL5Cq9yJ2J50RURYpQC12jAYpNwoLmrZLoUVHJv2um/VlhQKqOwQYC8BUHZmnU/QQfVGPDMy0JPc+uf33lxRPrX24BKhyezMMaKqhYBPgSJJt8vfJnOU8sNXFKjV2xXzWnM+Z4puhiSrMrSE6Se2OX9Ded2LvMK03yOTnV1jjQsbQv+XIf6zex1c+zChhMGM2UWijDFjv2PqighFVrXVSiCzwbZAgNZifWoip6VBFZoTCvFTUYMOgOkIU6SazJOcVhoJxzR4BQXxc1tlEHpT+mlI6DQP61JoT7Cw7GgZU+ZEjvrKNGP91jqD+QC8xfsJPQEtd7EkuLg3IEwe39ysGpKathX7YwhAlkBih80y/6qgw==
    admin-user: AgBQbENeigS2bJpFRTaiqANked6Fzaps38UpZQT0Vq9i0Vpxn2QdcCjXn2wM6JVXeyaI5s/TeiQz1leTJZf4Py91UVseqmDKOcQ+K80mYNNLVMx4D0GUy+c9Rz43NiFMyONCbcOJvYlAJmVG4Jrb7VWYaFTU0XphCR0yaL3WKsmrr2wBVxYwFjrRo7gLC7L11tb3NY8uAUYZ70zRcbYkuxDqxVcBR5jzzNu/D59KKBxJ+UKhSSx+4v2ckBwWvwacLw4glzybJyq5s0LksTXn89PPP4rd1gLcI5Wc8NYDAvZMjrT4Af7puWNBmiVYk8F/Qt+zYF6GhvYU7jI8W6HeaooZKYkRNA9+J+gWhudAoMzZEMslbwl6djro1X/1h+5URW0DX/HvooyOOQ5tGrLkyhK0p67uR8PG7NCDNtEwDo/+6dXqh4mygBl1YxlLK+MfEKLb3IWR68mxoplWLANFZfvTX9jTU4oI6wnqikwYo294VABo+VUV+fkTffLIPcwWc0DsWY46JmAIKCjBX9qFuImzOdWKki/KXUQstxtk4DrD5Nsk4gmK5ZxdPjjVJUpmh7QOfn/uFzRX7BQPF2iOYRJbozOXs01k5SgjystHG9ZpWG4BehYuJoFlFhEh9CTtlpmWtjBeWdT6MERzHg5aX2R3DHsXl9g7wUqz0rFOsph/0UzHaq7CcIf3RBM/zHwYqdZPWJwT7w==
  template:
    metadata:
      name: platform-grafana-admin
      namespace: agentic-platform
