---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-grafana-admin
  namespace: agentic-platform
spec:
  encryptedData:
    admin-password: AgBTT9A1oOKuWDpaDvNuTaVH5EEzRDlK/RFeEZBgpveAMy9PDuiidSaqsg3IeVw/1eNWBD56pABrFRIqvi0ajZ8aSpguvhPIcfx0zwmaSGU68Fym4diYHc1bGopSgKs6FvZDRfUu10PCVvy19mYtDpug6q+4FnvsybXo4aYKQbYuJxqz5Scsd0Ot6AXvAy8Y75JKvlODSBSQg3ACfa8voaU9KsNyNYAjGoeVN3OUDKW/PGke0qxhvzPonHaI5MuQ8Zv11CTbc0m53tmwGBlrDF/X9HGTRFJO+g4POGjgmHwSZXuzpZiBOLfM/s3ui08zRkqkTHxn+/avhGUQh+4xRww1SEfUW3UxFv+HM1duabb/C1smrWLKuDSSjqAZljd0nF0f+HKw7JmZXb5L+XJdVEKLvsuQdVd7+MYqB9bSG9QnGVhzzdR+PYgcpZfQMHPiMaCaSJixNhoqNRH+lDmPWAzZTuNgVXiQi5lTr+Zmqe1wFLklVzAVZ4hoTo37H0zbZOofutBKgL/WEFbzJCll3907SHb1dKHrHLwNyNQpDbi7oV7i+dGrAGTZER1gDlUs++cI1ZRUZ17yFvrtDDzIxrV8ffll2tTxoUrkkM1+y3XtmF6P9C7EDfWoO5Go2+1DBDFOPY7TIk2bcztZvLPqdtQ9TQsbPhKAgPn4pLzBODMSEKeqrzNRAHsRRQCnmjuwCnHJKWgvkRilRbY=
    admin-user: AgAQEc+mZ2H2xtVelODdcLagB3fYjQVH+KrP+uEtQ9QicHvb3hb42YqY01Ou/JKBpphNLy47n/rqyS92MbQv3b+Jn3PM/oYT9sxyplH3+zKQPflWdFAhqAffsVQafB5cDkXnOPS8E3nMrtqnTOZfN8IQT18DMNYrfwm+xU15zdK3gY+wPaD51rC1LWfFMmFYKL7WCkN2K4PYaXaqWac99q8nAxxeALc6iDqm8QlT6kOXSB4zPc5WEr5ztZjlVWQfuqXLpa2BI4mzw5XsL2A6wzkkcFrtJz292V9AEAndpgapxE40eeYbqkHnyk6exltR44ISDG+khVXL1+2EGozDjYrwviJrFtP4XeWqOqtkUpIMHppcSCrEJeHttmjk72gjkygE8MuEtGLRk6L823UmxS2xau2Beq93nri9xYlfbd/U3qv7rPywa4rmkS7TEhfe+ytTTXlPKfCVfQqTOLRoK4igSipaNGWtmhaY1YD3kdHG/6ZV0dNT1tTEZcbohi6RM0T9vWtlS5zH203dSERLYaiTz/sAHrAFJsT9EpoNaGo5LKidPnhjWVcovNxXwTN1jDbuxf59mStwj1j1gn1mLWmJmBXShZh7xIhBsiv1acriNtkTJfhUhpaVGD1GYadYqSn++eAWQR+EE4Vpxs/KXVNVQ55U4FAvIHLJyHyYjZZF9uVpt8PBmeXvneBFUOnp72Wo8VD3qg==
  template:
    metadata:
      name: platform-grafana-admin
      namespace: agentic-platform
