---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: enterprise-platform-grafana-admin
  namespace: enterprise-platform
spec:
  encryptedData:
    admin-password: AgBTAs7O7B+glxXPuECA5KplP76BHp+YhbMqVO+mDzW6zRuYquS2WW6++Y9IDm4ts+Mw3dELvKb2LJMDJzoYF301CIzDaKEpTT8rSmrl4BcFLPKvtbYAr5ezntWzBmW+A9WiN1R1Xy9Wf80V4Gq7qBVTtEBhMbSI1tJWffJBzqZcOz5NpMpHh/Jkn6dO/q18omJgeh1nSWFa/4MjcJgze3u5pJANKiHEDiO9iBdhh1rkG3x5wdEuYv/4Mle98bM+sfTayw+leSQcgxOjZaU1O/XGem7elerK15F9PiQcUhkshw01gnStmnq79yoeiIrBksIKS10gXDGbg7qHzi75C0oggimsdBj5cPd1XVJI25jkqe+hLfBSMzQDVmypJm7t5JSCl+NBUyOp3AdFuX4tnbL7SSj0eQPlt+LkpJACaDlWtLjW9HtI9Oj26X/VUZdTs5nrwCS1hAOruEG5ty1WvIPVqa89Ay+2vOhdiDNEWklFa6V6WkN3BaiVDrxP7RDsTgN/H/bZrJSwmt6bknoiS5bxJ8jaCEru9SzS4P0wsCBn+LxWSN2RFWZB+cPaBbywE+ye9q6y0hd1oA2wirWEVmdggL7ZW5TLacmSWLrlnaGvq2TXyJKBhfOhnZ5Lax+fzVyUOJzSH1OPI5H8V/kykSqeb5m2oQhAYZmJLNs2d/LyuSIEpzXntTtqBTCVFZCAQyy/RbO/zpl1zg==
    admin-user: AgA2P5YhljiSwZjkY4X+yLrb6AJ1E1UF3Y3/RVAbEFq8sswBrKmCf6IpBNDpjGbig2S4JdnIL5YR5ht/o9/hbjjnKegpKzA80Yt+qvsHw9nBy8RkxBKLGm8yN4h281CyvRZHo53e0zfstTcWM89uSMZRkaFci2pRxfyWKHKPoputSmzMmo4Tg9lfifG3KDTO0qSIbVNWVj+J8bi1lbhPo67FibLMVKUYHr2gr5mQzFg6f3060yvZ76E7sbNVNN/GLqxjOW42GRs9dZCe0kp+yxJy1lKkaPM93mAeqXugcAa++DcZj0u2YBt+rE7F6OjcQbKwl5tPnwaXGUSLjgIWQm46G6FVYbtDV92PfZDUS0vmiGh6cnqRTmTDjwY6U2Vkh6QrxiUkMG5+kNeVYEEcCPvA7MmHYlFLp6tzsvJIIc41er9muBtQfwTdOa1S4p8bMsessNOSmdSzeS/mkjap+KKUVjOL54S37ueFI4PcZavkkygPFl8g8SnRGCki2uUieNEwuio0BhFh39VPg9gt8OaezSBM9yh6RLKZHKFybtIoBd2LX7/3+MKLdMAAWJiLBZM6LXZmvcpyZSE6fTgoVvI7I8G3x1SI9LzSl5Uvm0AwX8/xuq7EtxsclCZyeF9CaUsQGvsMXpTjrjlqmX1X06DGY70d4yb0TAR3swoGL7dj1uqqwnHok6ke61nN8amA698uuqq+Cw==
  template:
    metadata:
      name: enterprise-platform-grafana-admin
      namespace: enterprise-platform
