---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: enterprise-platform-keycloak-admin
  namespace: enterprise-platform
spec:
  encryptedData:
    password: AgAas5/WRTTEJUiablw58Y4txPhYa/9UEYLFDyofv6JbltLjMsYlghJq1qf+8oDoshCWlh5tMkSuyLrDzlPPwo/7fH9PqwyyUUt17pwRCsSIJNUO04qCEih2gvRScQW1dQe3uvDsrPM2bM6Xz77a8/d2WL8GVZ33Fw2RUTRuyfiaoxOVC4Aglu2E4Jyl3FLGr5jJe268WZlR0xX7fjpBHQpydMnKYfbncWEA0X0UOaoFgdLh4lbb4fu+c7GZ3/13nLgDIcw3KeY0ltDLyMs20OpfhgR0dypNE2Yr4bOnQDAOIoBctThgBPP6INZWmTFybvJT3VAAK7RtKhailVwfu44CO0Qn5o6Yhz6rt6FdV8P0Metkue1nxCZJ/Z3jCJDTHJSIp1VhKpTEQJ5bq/o3Z0NlW1BtkfvbzyPI+RAZ/8FIrwRI1cac/jMSB8fQQS50KMzHSAKOiPzi2xKjPitSn+stPJWuRXtA0bixpUyPhC/byv4sGNKJxKc4FIIgzMtPC13jBVBU91Ka4eMjmzp3zGryCJDyitsa6OoCNwADjkHx7beD53gVP9IXDPY9YOhEz72rI5r//Qys4QzrMKHhkrwkfWPH5gNx9slnMZgKPtSWqRFza77RcbQMJad3EQ1klowI0CyY0rFhi0/Afbqzqygbr+Fjc4Ke9rgiBE5eB379XZoWN/zdQKiqYJvhs4Dg43fRl4FzTPz9uw==
    username: AgCHERTuU8ObJaTuMjfsYpORDKDcKNhRbEYza2p1JI+Yit2VS8liWkuVyx5cfL3IQiQtouzWV2blY/fvrFCO1yKrNejU6noPNqzm4TePj6OysQ7nRdTDh3GuoJ78qQO5/z271poAwldgcbGDPq6P7u2W0eRADKnjwCICFZ1vjLVNZSdqMW9wVL8wMi5sDx19PfvofUzLyBjkxmnRuIf348Vj6it62HV8s8SY194A7uOzDBIPuOEEmD+LtO4ksltPPNENj+8ZI41XLKhFcuCUAHge8RfVp4RbrMBe1+hvBtbsQZdnbudkE66QfQCoggohClZgsxZN2TuWUbhS/I3cXm16tPn1Ubz63K+m84fBf3pJnImF3I+ymSZLC/e7RXnVku4A8KtE8gD2tCavHaWL6naF70tIcWTlSjjZ8obgQ5pZpfS3MEvuC1yiyAtpD3UKnoY4IJZmlD+F0Kgx6Z05RA3FvyIUN1OQZ0xABnBTlDOzav3qtcEseoneNO06+3noYH/B1IHAZrfQw18jYPju3vnZ74aSpErBwQmmjv5oQQl035fZ9DjfalBDTZYkKVdWs6ZZmLY9Ix2P8jEIJFwlNaKp7wbT1oJW93UyQ1JGaMuRi3lFNEMl1BvcG4YG8svoF+v48xDSYUhY5UNbQ9NIvt1qV3rxqwRJNGXedfo2cG8vBSAteapxYUhK9/VuMxZwUQGyDVkCww==
  template:
    metadata:
      name: enterprise-platform-keycloak-admin
      namespace: enterprise-platform
