---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-keycloak-admin
  namespace: agentic-platform
spec:
  encryptedData:
    password: AgBh545bOUoTOk7c4Xc/0oYoooM5bIPvmhRbR6NL7Icg5MeF6nR2zvfTqp1UbhMEPMjgklOG+fj5nIqDnx8tHIlebNGAQXqyyIQZT60ft7rQ/fYzSnF3Mitt/AJd1Q7nxtQ41td/it9sJbbgCDsj9dQoiXSnh/Pz8B0CF/dH3P8sOEAoTtrqQTq8Vx6I4orwlyB5KsTewqomYJLWp+e4VULP0926KliYLWNql5tjlX/Ev0FyAgzwdBWe/yaS15o/S9lrykHIN6qdbyDzbfoRoO+3VFrQ80rpBuAT0tNtqCDZJ/TAiNrm6C3WVhqYBYm6ojHxqM1VChk5EKe65hTZukVQ47N/dH6BgfZXLo0ivWxgA5d5vsQeJ/fBXuxm9DgM1D/6wZrPYPykN8psiC2xhFFeXim09Y04DOh4wMS0oNY9S0m8EdtKKLVYB8h/PT2Vvq9f4b44aew7kbphpetZBSLJbZaLZzi1FE3paWVbeVwKCE7RTGDF/E1+uJ2px0MQwZrihYA45syj4USB8uThdvEXGRfKZ91MO8+LP60afb4+8S0b9c/kV212nDNEWxe33E9JdTUs6fPTHTIWBVhZxC4RE3ZUSRf0jw+5GOQp0jd/zIKZim55Z760nB7lk+F6uVo7VtuOhLq2LB44EvEUB6/EcczW1ItCkI4OPEDNnxqdLvstx9idb+rFajtXWqJI9xiE05Mu/A==
    username: AgBJFk3XOKTyQUVdDW8Xkhkr8JZ/uAXDKeXeNMacqp7Qj0YQospChV26UHtCFs0lZD+moFPwMaWRvAgD51S2//hltCDcdldPM8FAJE2G5ddxtljHkULpxAw8cyw4qmgQiRJVd0yP/1WuJUJZ/EJ4BJ6r54Z3nwcsBSp8EPEltNTbmI+iXuwlssQdwRwUKLATNcBqDgWyraEW0e1Cb5iXJ/UdiC/LDKJE6J3dNh3FHZ97jdNC26bel74jdYZxIB9pA2xT+3Zt4mCmYkDHjVGqQrgWku8zrUkhGrvSMQSZ0MVwTUdb6YgZiIfCxN5oz840tf8scKIJHr88XKh4OAUgk73w5guJYERUTUJyTqpYj3gILiNIJQqs5GOpmM4A2H5pGc+dqBBLWDYEOmlm8ikC26yFwNp8XO8wznSoxR5IKJXD2NAoNdbSyOSA3oPu7fGi3uuFAHqRmhpXVTbQgQknfKWzCBn33kYHRgLv7jjHU8OXS56RVqRtm+EWtrMPAWQoVUWe4IHVGpaQ3Dp/uYzK5jzTnO0aS01v/H3ENWSJTrgCeDnCYockGyTk9BzOEX4dEplJukoAuFZ94c0qNC32W0wBjBkUl4gvw+H7VhiLQSMNClSrNopwZL69eOK0pif9DXteCzVjnecOFw5w5CWg95qU/8FZGFQbdlZ5xoEFpMncHuuPOLerg3P1ZEGQ0gGYT49d2psfEw==
  template:
    metadata:
      name: platform-keycloak-admin
      namespace: agentic-platform
