---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-keycloak-admin
  namespace: agentic-platform
spec:
  encryptedData:
    password: AgB/qgqSP7qLNL62mqL8kk0bBVMaStY5aNtB6c9psVxswdcr5JTw3p5Obv6/c5/ihT5AXf6vhPWMJYTlpYszco0uKi0V4daXt+ZwBQeaLtXpxzCg3qm4jKWx7FGurDFTbR88aBPp/22arqz3hPcoggXhDbj0BMYjDYBR4CTwbTaIwzIZT30NbPWqgrkfb1nFjGq+X/tUYEaS3cw9G/tEhgUOWSFNt8P4jDsZz9x3bck2tdGwHXQntr0iBMI6lMmbh5BLcnepVoXaPmrVKb3EYBdQl7O9kP8RlNzDzghXkitdSN3vmC5zqMkn0ytJmnnobyv39td26JTqOQTxVKUnZJFVo//eivjWxX2pcapsKAmBlV8rRIsvHRbvuIDROc8G0mE/fMBKdD2KinUcAgWrhLvyPOcP/oJuTMgyUyxdEGsUnv1Ko1m+Bq7+HxsQRHNU0/J3WnaUmesyjOdTopmT4LgAIvYVHOR8mjX+K/3Fk9R01cDWWH37qCVLt8AGCASOvOdZ+ERkkWX6altetjJGyH23mjf/EC74WUecpWUiMVWYNBvhgx7pxFfWLK9QcZpTxhHY+fEfwhqgUZxYkd5XmaRHRKwhLudlLshx2yvY87tNAZWZhWRjHM5rwrklQpwfag5GD7bOCIODimGz6KzED5z2YBH8sB5jQLemet5TagZVLddROZzrjb9FEjXaf9Mm+7cuIml3J072Gw==
    username: AgAVqlx1D+rI70m42CYXygm9UsTMwbtGKS7r3CDgk1KYYf5kLZCKDN5O77HMNTxBCzqKFvzlyBeku9Er7WsBTCtDzgfq79iO7HUSI8GyETHCKHie5BLgkXezUw4tmRKVV2uKzE7z58sKdlaY7OBS7hJL4+GIXoNh/wLPhEmh0Q67yQt5cC5Fq9MGOYkRIPdab84wRnQj4b3b/MFyDg+/AkvBtghKWDqKxLJG52Ozdw0IyOKZrJOJuUUd498xHhtZlwqQYgzKDuDIPwZZ4RD1/LpA/ic+/UOimsK2pL99Uan+xQcu+pvq57pqmYH7sbQA5D0fPHTQDLRXRP9pakGKPM2oeuGviYYKBCffn+kHtlM/zCyXQpt2oh+BazNO+YmjwP1sSp4hWCxmahmJ4qZDyMjuO5t3XKlp+9O60ShvJ9bAXxUdCxZnPCF6HEAHjygJZNGnrgJYEl345gujQwqlmwyBCZvjUIzBg8Figsswm6Mmjyea2bjHYV2DOUz+XCE9NMDjHV6Eu3qu6hMccK/0Q72CP6Jsmando8vGYXhRky6VpWTNEKnlFioijNanYRom2Lj479s65DXEqjwEpEdkBqbjeyGqLp3td6XnR2fQw++AZju7eGCBLFI6YJj73dQ7yVGD8nUP0IaUoL1c/Q6UZ/yOpHCBpvlQeVwPQ2CA4/Ja9/5SJh2JwK/JNvtARFPC3yp/Wsfn4Q==
  template:
    metadata:
      name: platform-keycloak-admin
      namespace: agentic-platform
