---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: enterprise-platform-litellm-secrets
  namespace: enterprise-platform
spec:
  encryptedData:
    masterkey: AgB8SieKEqZsEzOyIQkfjVm8ZjRLouP9cZXlDbohGCtX14B3e/nIvqjnELljj05h1vKlrLhFLa4kAoAycxPDSVJjnjk924yZYUOtLmEn8DbH7utLghdu+0QmzbVyTIdnxAmOWAeH8xuufNh6dB3m2YFcD7S6f72MXJzAesh9MqAPek1iN+TZEJ+p8KTWoP35jlqZBof/BZFBU0R1S36rNsOgDBBRYJVTZUtxu5oxiNrPy9o4N/5RNdc3ROXTd8pUqV1LBgaUdOjHyOEdCLHrRsW/cxQ8otmPUcIIeMNCsXZTrFtMcvO715nkyWqRPGFx71x9ASZNg9y+1oJh/fBNxYwpZ+/C0fZkOjkAq56r2ZB2R9aXKW1d1i1fv82BFQ00y1tGqXRMh9j3YKhP1brOV1xqqYwlTgmo3c0VRwQWwRuyoGI9q+P1XSShoeg6exIHHr9W/6bgzVnGXUg6B8L9un05T6ka4Xi+61F3/khlFccmWmUz8y/294F3J86aDqqx4DkKcPx4BSH8PX5qPf0WjbjUcz8IwnW3HURj12gL5heoAztYZhfqD1KGsMgkiUw9SLKqchWnboBJXrhiJxZWiMydjEpjERCI7aAp+ofcbiA6IYXvjzL1gnHsfaB+O7f2GkA+1QTDk2D74ZAFz7gtXFxFNs/Io5As0KLBvMJftSoyKeydWMytp+tpHSkNj5Yce1tcqlB/HmeVlXriDMU2ZnHsPGT0muWjILY4yR9/+bd7KhZokFATJBgY
  template:
    metadata:
      name: enterprise-platform-litellm-secrets
      namespace: enterprise-platform
