apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  realm-agentic-dev.json: |-
{{ .Files.Get "realm-agentic-dev.json" | indent 4 }}
