---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agentic-enterprise-grafana-admin
  namespace: agentic-enterprise
spec:
  encryptedData:
    admin-password: AgA0LGkKrVclgn3I1qFE8StVA5ZV3IjKsaJkbqFBl9aGgoOdCvOnEQdyVuH+OZMU0C99VLaUo6ZJpBsKYZUdK6LzHv+6eMNE37NCmTavpa+fbJGoTuXjZ5no4nsszTzAiTDHPzC2/hR6wlHyatf0d//qKUeeQd8BV2bwowmEFTdiGipy7lgolrlX6NaqR7qQPJak16EnvEFNk5h2y7oGpxfguqBxjFTwN7cYBh5Y1IdBoqNAoBRyj/ESqpubTA+tuO9Jx9RyOobKddvlVHBNijboLsnoVwGqlEIEh5+7Isj1t4N72IaB1MngKcVqgZRpzqnVnH0DGJJjiXAoWTvpBOx4iA/ePIb2kNlr7POT2Ptps74BcQW5J+bQ7Dy0sh7xGPdbI37+gizrxVZ0zyA4gfqvkmtD7W98OHGGLMbbdGYAXA9FxFy08m9Azor0sQ5XEkFtIhGHQijh09TZrgX7y3HlJS+Uo1uFQrFu6xNyadAh8ikEknscZpqpHiPeHpldQ4mUeiZIVOLdohxgZimaRuMqwJL+FjaX6jA+jCF36TLQ6gWZUSN8un3OlMC8y4aE27Q3NguVv9VM4CgxQXO3S1U2mCqC4veo/5IyyEp+TSFzyonYftL0t6ddzl0hOVzt7PdnVR890t9cN6hWlelrI9W7/SRReTuZiCSbtVtzWdnUsqMVRo51T/Cj8yjPP4XmQtQrjNio2w6CS8g5b4XVZ04qS6rTh1fMDSa8sM6ly+v6PDM7v+ASU6Hem4ElH5hZ0Vs=
    admin-user: AgAZpE1BIBCYG6y8nPp9x27VyLMjwdmpp0yxC0MArWgk4nUP4ThtxyIBAzboZgSkbqkZ/i/XSe7fQ+6YCc6ADOPOqUd7WmPuTnzSLr1TiAmFiQWJd0/XR9NtZu/eUnBWcsJqlLtgoBMy7TDa1j9b/YtseZPFg5OkKI4OjN3DXQgkE34ER0mWxhLTz0KIuy/tW4tLvSTQc6/sqjkmeQD08Hhv9DyKBY+L1lqNJaqe6p6Rn9Q4Xzvz/3q2sqtkqEv2CQTiMwnGhVqBcdps6XrUFu8bBZ4aIoQl7so19kgcOEg6Yhs1a68PFmSjHMub0HASMr9j2waNPP/0rVZL9vzB1B7SQeVglWh6CueoBeiMAs7bA0227K09Ev10Bkd3qBXLcmTtaZwYUtDvpiT4UOOBI+MGPLGKpq1PGAIEwbLCKwuDz0SHGqHLevZGfM8N5cSM6BrBZ4mxpy6lgz9W293Tj7eZnOcqbE3sV/9aVPq4TMEKN23NuqufOcc+N/aNb7xlyhASGVVDZBv9DAOQuNg83az9ZQCNPfqBiup13sLj4Ddb4RefqdU9fsHgs1PjY8cOrR48C6FHNyvKeyRwIWfN51oVndgyyasrXBVSVumnV6c1hrxB2WEW3aVqmfV/66RyN/UgVEyjBhLTV5EAlegGq7SsiI+OOX5abiXU2/1OdS2mIKlWIiDG4hzxAgfc/eiF3yN24l5csw==
  template:
    metadata:
      name: agentic-enterprise-grafana-admin
      namespace: agentic-enterprise
