---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: enterprise-platform-keycloak-admin
  namespace: enterprise-platform
spec:
  encryptedData:
    password: AgBJpIHphSjFEYTS9Owpo8etGxNuNcsskpbEMXlYin+jOgdr6M0dlZ5YUZqhAG6kwjiWq9MHDkZzmw9QKEucyDi3/xCEI6ijMCoGi5ktoJ6ikzl4ulyYToZ/lqf/cCGC5Wu0LUBeJDPiuUBAFGuNfn3Xgt2mh+/f1uwasaWSNRry3KerHfAWrhlHwSKngaTflcc8/AJi7ST4+OlGTrSjtxeO18iD11gQdvoNYtwNqGRztJkamg11jOQAgEmGXUw/2cB4XlOnMr2F7a2MqRM72hqjzVHOqVREju/OhXbpZJ54JpkofQZ91+5qfIHOLDpgPjMwjCL6rfx3N49MrXlTG+1CLOMcsQEbPUPtxzmj1Te0coOt1Y2DwW9kjJ5BPqqvqqe8b1V8Au+Z16ACmHPQL2GIlwHRK0pfh0Unr7yAmz33ZtLRuMIgZWACzD4W4+eFLb52/0iUisj3e6PQU12T+5eYI5drySGXlfVug6sWKm7X+4W7ixydL8jQ4scn5qdgxHKkbtzRC5rgUFVExW0wnRBRZ4KVhW6i0WcjRwBBGhQtIzf+GMhfFSKLc0l2EEfcWXX3cTjW+CFkpEb3x1Y0oVolnkxe+HvamNRgBbVB9A8I4TNzWiL+qxJL5ch0f2/FWJmKzo5nVdvAJ4ZYyWLUtkkonrXUVnsEK184e8oWgqyWUt1cHlOUVl9GGXzJHC8O6C1hkrKwlh9uDh+CLJ84zc/EdQ+NM9gLtCm6HUXCK5GfTw0lEgphYHGSpefq1JzbZlU=
    username: AgCbvKE+Ji9IdAmYpT0nf639vmnLhRo7uS/F0FXMh5fFC9RYZv8Z6GDjZ1ZrtjlHxqjThdlJ+naUHXljty0QMgY/gRZWXo/f1NL9YSWic4IdeS5wCGK5paXcPT6jVgFIHPtzY2hSLTyptkc/93UGJqa1jTrX1DfNmeCMv0TWmvR+Yf+AqM9LebNdPTMHoo/c2nNl0zFcFRQ0MChoUKczUxDS1lVE5Pg85VVA8Q//YEfY5C7iLgNrk9apG8f/XnGkvPoqSWjiopR2ngKnzmhcXYzA6ienmfJwUVUEn4q4yLfOKKErVbVMZDdMzoGcgHq7ZeMNvhT+6BWPa0I0ZOGGqHN/y2IrmqD0XGotTQVW4kZgjhJEv7c5C+RevWRrMgivh2r8OpZz++XNszrgr2jGIEBB9xbePOpxeLpUH3ItgzK23f96821oQcAXeh6yzMSbUNvZfd5Cca0ra2Hvi9XEuzs+uFxWJA0S+wh/sjSiURUNPkP6pjEEsTi/wUbkE+NyhGjeXUY2Cz4poPMhFlAEorycEmop18HJTULAW3wS+pNz/Ail4bIian5D9Nr4X0QjGN6vf8oMN4ZOkGP33RVEK6HtfevMW1adS0QQVAy/sYD4nR7c3H3oIqzdQP/GGEFXoeR8mJT8uSu+KYsw8lKCyNGFtoanWEDaW7R1iBaXo1Fe9qGbyYHKpgjH7el81tSr6GspWyonag==
  template:
    metadata:
      name: enterprise-platform-keycloak-admin
      namespace: enterprise-platform
