#!/usr/bin/env bash
# scripts/gen-prod-secrets.sh — generate strong RANDOM values for the prod
# secrets that have no external source (DB/admin passwords, the LiteLLM master
# key, the SeaweedFS S3 access/secret keys), build the matching S3 identities
# JSON, and write a source-able env file of `export` lines for sealing.
#
# It does NOT touch the real provider API keys (ANTHROPIC_API_KEY, OPENAI_API_KEY):
# keep those in your own shell/profile. seal-prod-secrets.sh reads them from the
# environment and aborts if they're missing.
#
# Usage:
#   scripts/gen-prod-secrets.sh [ENV_FILE]          # default: ~/.agentic-enterprise-prod.env
#   set -a; source ~/.agentic-enterprise-prod.env; set +a   # internal secrets + config
#   # (ANTHROPIC_API_KEY / OPENAI_API_KEY already exported in your profile)
#   scripts/seal-prod-secrets.sh
#
# Outputs are written OUTSIDE the repo (under $HOME by default), mode 0600, and
# are gitignored even if placed in-tree. Never commit them. Values are written
# only to those files — never printed to the terminal.
set -euo pipefail

ENV_FILE="${1:-$HOME/.agentic-enterprise-prod.env}"
S3_JSON="${ENV_FILE%.env}-s3-identities.json"

# hex output → safe in shell single-quotes, JSON, and --from-literal alike.
gen() { openssl rand -hex "$1" 2>/dev/null || { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }; }

POSTGRES_PASSWORD="$(gen 24)"
KEYCLOAK_ADMIN_PASSWORD="$(gen 24)"
GRAFANA_ADMIN_PASSWORD="$(gen 24)"
LITELLM_MASTER_KEY="sk-$(gen 32)"
S3_ACCESS_KEY_ID="$(gen 10)"
S3_SECRET_ACCESS_KEY="$(gen 20)"

umask 077

# S3 identities JSON — accessKey/secretKey MUST equal the AWS_* values below,
# or seaweedfs will reject the clients (tempo/loki/mlflow/bucket-init).
cat > "$S3_JSON" <<JSON
{
  "identities": [
    {
      "name": "agentic-enterprise",
      "credentials": [
        { "accessKey": "$S3_ACCESS_KEY_ID", "secretKey": "$S3_SECRET_ACCESS_KEY" }
      ],
      "actions": ["Admin", "Read", "Write", "List", "Tagging"]
    }
  ]
}
JSON

cat > "$ENV_FILE" <<ENV
# Generated by scripts/gen-prod-secrets.sh — DO NOT COMMIT (random internal
# secrets + fixed config). Fill the two provider keys, then:
#   set -a; source "$ENV_FILE"; set +a && scripts/seal-prod-secrets.sh

export POSTGRES_USER='postgres'
export POSTGRES_PASSWORD='$POSTGRES_PASSWORD'
export POSTGRES_DB='mlflow'

export KEYCLOAK_ADMIN_USERNAME='admin'
export KEYCLOAK_ADMIN_PASSWORD='$KEYCLOAK_ADMIN_PASSWORD'

export GRAFANA_ADMIN_USER='admin'
export GRAFANA_ADMIN_PASSWORD='$GRAFANA_ADMIN_PASSWORD'

export LITELLM_MASTER_KEY='$LITELLM_MASTER_KEY'
# ANTHROPIC_API_KEY / OPENAI_API_KEY are NOT written here — keep them in your own
# shell/profile. seal-prod-secrets.sh reads them from the environment and aborts
# if they are missing.

export S3_ACCESS_KEY_ID='$S3_ACCESS_KEY_ID'
export S3_SECRET_ACCESS_KEY='$S3_SECRET_ACCESS_KEY'
export S3_REGION='us-east-1'
export S3_ENDPOINT_URL='http://agentic-enterprise-seaweedfs-all-in-one:8333'
export S3_IDENTITIES_FILE='$S3_JSON'
ENV

chmod 600 "$ENV_FILE" "$S3_JSON"

echo "Wrote (mode 0600, gitignored — never commit):"
echo "  $ENV_FILE"
echo "  $S3_JSON"
echo
echo "Next (ANTHROPIC_API_KEY / OPENAI_API_KEY must already be exported in your env):"
echo "  set -a; source '$ENV_FILE'; set +a"
echo "  scripts/seal-prod-secrets.sh"
