name: deploy-redis
run-name: deploy-redis

on:
  push:
    branches: [main]
    paths:
      - "deploy/helm/redis/**"
      - "deploy/kind/kind-config.yaml"
      - "deploy.sh"
      - ".github/workflows/deploy-redis.yaml"
      - ".github/workflows/_deploy-chart.yaml"
      - ".github/scripts/smoke-redis.sh"
  pull_request:
    branches: [main]
    paths:
      - "deploy/helm/redis/**"
      - "deploy/kind/kind-config.yaml"
      - "deploy.sh"
      - ".github/workflows/deploy-redis.yaml"
      - ".github/workflows/_deploy-chart.yaml"
      - ".github/scripts/smoke-redis.sh"

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-chart.yaml
    with:
      chart: redis
      smoke_script: smoke-redis.sh
