name: deploy-postgres
run-name: deploy-postgres

on:
  push:
    branches: [main]
    paths:
      - "deploy/helm/postgres/**"
      - "deploy/kind/kind-config.yaml"
      - "deploy.sh"
      - ".github/workflows/deploy-postgres.yaml"
      - ".github/workflows/_deploy-chart.yaml"
      - ".github/scripts/smoke-postgres.sh"
  pull_request:
    branches: [main]
    paths:
      - "deploy/helm/postgres/**"
      - "deploy/kind/kind-config.yaml"
      - "deploy.sh"
      - ".github/workflows/deploy-postgres.yaml"
      - ".github/workflows/_deploy-chart.yaml"
      - ".github/scripts/smoke-postgres.sh"

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-chart.yaml
    with:
      chart: postgres
      smoke_script: smoke-postgres.sh
